core/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('core/', views.CoreHome.as_view(), name='core'),
    path('core/about/', views.about, name='about'),
    path('core/addpost/', views.AddPost.as_view(), name='add_post'),
    path('contact/', views.contact, name='contact'),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),
    path('core/category/<slug:cat_slug>/', views.PostCategory.as_view(), name='category'),
    path('tag/<slug:tag_slug>/', views.TagPostList.as_view(), name='tag'),
    path('edit/<slug:post_slug>/', views.UpdatePost.as_view(), name='editpage'),
    path('user/<str:username>/', views.UserPostList.as_view(), name='user_posts'),
    path('like-comment/', views.like_comment, name='like_comment'),
    path('delete-comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('core/notifications/', views.notifications_list, name='notifications'),
    path('core/notifications/go/<int:notification_id>/', views.go_to_notification, name='go_to_notification'),
    path('core/notifications/poll/', views.notifications_poll, name='notifications_poll'),
    path('post/<int:post_id>/pin/', views.toggle_pin_post, name='toggle_pin'),
]

users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import PasswordChangeView,PasswordResetView, PasswordChangeDoneView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views
from .forms import UserPasswordResetForm


app_name = "users"


urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('verify/', views.verify, name='verify'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),


    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url = reverse_lazy('users:password_reset_done'),
        form_class=UserPasswordResetForm,
        ),name='password_reset'),

    path('password-reset/done', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',        
        success_url = reverse_lazy('users:password_reset_complete')
),name='password_reset_confirm'),

    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete')
]

vault/urls.py
from django.contrib import admin
from django.urls import include, path
from core.views import page_not_found
from vault import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls', namespace="users")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error' 
admin.site.site_header = 'Панель Администрирования'

core/forms.py
from django import forms
from django.core.validators import MinLengthValidator, MaxLengthValidator
from .models import Category, Post, Comment

class AddPostForm(forms.ModelForm):
    cat = forms.ModelChoiceField(queryset=Category.objects.all(),empty_label='Не выбрано', label='Категория')

    class Meta:
        model = Post
        fields = ['title', 'content','photo','file','is_published', 'cat',]
        widgets = {
            'content': forms.Textarea(attrs={'cols': 50, 'rows': 5}),
        }
        labels = {'slug': 'URL-slug'}



class UploadFileForm(forms.Form):
    file = forms.ImageField(label="Файл")



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={
                'rows': 4,
                'placeholder': 'Напишите комментарий...'
            }),'class': 'comment-class'
        }

core/views.py
from django.http import Http404, HttpResponse, HttpResponseNotFound
from django.shortcuts import get_object_or_404, render , redirect 
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, FormView, CreateView, UpdateView
from django.core.paginator import Paginator
from .models import Notification
from .utils import DataMixin
from .forms import AddPostForm, UploadFileForm, CommentForm
from .models import Post, Category, TagPost, UploadFiles, Comment
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.contrib.admin.views.decorators import staff_member_required
User = get_user_model()

class CoreHome(DataMixin, ListView):
    model = Post
    template_name = 'core/core.html'
    context_object_name = 'posts'
    title_page = 'Главная страница'

    def get_queryset(self):
        query = self.request.GET.get('q')
        queryset = Post.published.all().select_related('cat').order_by('-is_pinned','-time_create')

        if query:
            queryset = queryset.filter(
                Q(title__icontains=query) | 
                Q(author__username__icontains=query)
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Передаем query для инпута
        context['search_query'] = self.request.GET.get('q', '')
        # Явно передаем 0, чтобы сработал {% if cat_selected == 0 %}
        return self.get_mixin_context(context, cat_selected=0)


def index(request):
    return render(request, 'index/index.html', {'title': 'VΛULT'})

@login_required
def about(request):
    contact_list = Post.published.all().order_by('-time_create')
    paginator = Paginator(contact_list, 3)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'core/about.html', {'title': 'About', 'page_obj': page_obj})


class ShowPost(DataMixin, DetailView):
    model = Post
    template_name = 'core/post.html'
    slug_url_kwarg = 'post_slug'
    context_object_name = 'post'

    def get_object(self, queryset=None):
        slug = self.kwargs[self.slug_url_kwarg]
        post = get_object_or_404(Post, slug=slug)

        if not post.is_published and post.author != self.request.user:
            raise Http404()

        return post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = context['post']

        context['comments'] = post.comments.filter(
            is_active=True,
            parent__isnull=True
        ).prefetch_related('replies__author').order_by('-time_create')

        context['form'] = CommentForm()

        return self.get_mixin_context(context, title=post.title)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = CommentForm(request.POST)

        if form.is_valid() and request.user.is_authenticated:
            comment = form.save(commit=False)
            comment.post = self.object
            comment.author = request.user

            # 🔥 получаем parent_id
            parent_id = request.POST.get("parent_id")

            if parent_id:
                parent_comment = Comment.objects.filter(
                    id=parent_id,
                    post=self.object
                ).first()

                if parent_comment:
                    comment.parent = parent_comment

            comment.save()
            from asgiref.sync import async_to_sync
            from channels.layers import get_channel_layer
            from django.template.loader import render_to_string

            channel_layer = get_channel_layer()
            html = render_to_string(
                'core/includes/comment.html',
                {'comment': comment, 'user': request.user, 'post': self.object},
                request=request
            )

            async_to_sync(channel_layer.group_send)(
                f'post_{self.object.slug}',
                {
                    'type': 'new_comment',
                    'html': html
                }
)

            if comment.parent and comment.parent.author != request.user:
                Notification.objects.create(
                    user=comment.parent.author,
                    sender=request.user,
                    comment=comment,
                    type='reply'
                )
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                html = render_to_string(
                    'core/includes/comment.html',
                    {
                        'comment': comment,
                        'user': request.user,
                        'post': self.object
                    },
                    request=request
                )

                return JsonResponse({
                    'html': html,
                    'parent_id': parent_id,
                })

            return redirect(request.path)

        return JsonResponse({'error': 'Ошибка'}, status=400)


class PostCategory(DataMixin, ListView):
    template_name = 'core/core.html'
    context_object_name = 'posts'
    allow_empty = True
    allow_empty = True

    def get_queryset(self):
        # Добавляем явную сортировку в конец
        return Post.published.filter(cat__slug=self.kwargs['cat_slug']).select_related('cat').order_by('-is_pinned','-time_create')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        posts = context['posts']
        if posts:
            cat = posts[0].cat
            context = self.get_mixin_context(
                context,
                title='Категория - ' + cat.name,
                cat_selected=cat.pk
            )
        else:
            # Если постов нет, просто указываем пустую категорию или выводим заголовок
            cat_slug = self.kwargs['cat_slug']
            cat_obj = Category.objects.filter(slug=cat_slug).first()
            cat_name = cat_obj.name if cat_obj else 'Неизвестная категория'
            cat_pk = cat_obj.pk if cat_obj else 0
            context = self.get_mixin_context(
                context,
                title='Категория - ' + cat_name,
                cat_selected=cat_pk
            )
        return context


class AddPost(PermissionRequiredMixin, LoginRequiredMixin,DataMixin, CreateView):
    form_class = AddPostForm
    template_name = 'core/addpost.html'
    title_page = 'Добавление поста'
    permission_required = 'core.add_post'


    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class UpdatePost(PermissionRequiredMixin,UpdateView):
    model = Post
    fields = ['title', 'content', 'photo', 'is_published', 'cat']
    template_name = 'core/addpost.html'
    success_url = reverse_lazy('core')
    title_page = 'Редактирование поста'
    permission_required = 'core.change_post'

    slug_field = 'slug'           # поле в модели
    slug_url_kwarg = 'post_slug'  

def contact(request):
    return HttpResponse('Обратная связь')

def page_not_found(request, exception):
    return render(request, '404.html', status=404)


class TagPostList(DataMixin, ListView):
    template_name = 'core/core.html'
    context_object_name = 'posts'
    allow_empty = False

    def get_context_data(self,*, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        tag = TagPost.objects.get(slug=self.kwargs['tag_slug'])
        return self.get_mixin_context(context, title='Тег: '+ tag.tag)
    
    def get_queryset(self):
            # Добавляем фильтр, связь и обязательную сортировку
            return Post.published.filter(tags__slug=self.kwargs['tag_slug']).select_related('cat').order_by('-is_pinned','-time_create')
        

class UserPostList(DataMixin, ListView):
    model = Post
    template_name = 'core/core.html'
    context_object_name = 'posts'
    allow_empty = True
    
    def get_queryset(self):
        self.author = get_object_or_404(User, username=self.kwargs['username'])
        # Добавляем сортировку здесь
        return Post.published.filter(author=self.author).select_related('cat').order_by('-is_pinned','-time_create')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(
            context,
            title=f'Посты автора: {self.author.username}'
        )
    

@require_POST
@login_required
def like_comment(request):
    comment_id = request.POST.get('comment_id')
    comment = get_object_or_404(Comment, id=comment_id)

    if request.user in comment.likes.all():
        comment.likes.remove(request.user)
        liked = False
    else:
        comment.likes.add(request.user)
        liked = True
        # Создаём уведомление владельцу комментария, если это не сам автор
        if comment.author != request.user:
            Notification.objects.create(
                user=comment.author,
                sender=request.user,
                comment=comment,
                type='like'
            )
    


    return JsonResponse({
        'liked': liked,
        'total_likes': comment.total_likes(),
        'users': [u.username for u in comment.likes.all()]  # сразу передаем список пользователей
    })


@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    # Разрешаем удалять: автор комментария, владелец поста или суперюзер
    if request.user == comment.author or request.user == comment.post.author or request.user.is_superuser:
        comment.delete()

core/templates/core/includes/comment.html
{% load coretags %}
<div class="comment">

    <!-- ШАПКА -->
    <div class="com-head">
                                    <a class="name" href="{% url 'user_posts' comment.author.username %}" style="text-decoration:none;color:wheat;"> 

        <div class="user-pro-cont">
            {% if comment.author.photo %}
                <img class="avatarka-core-com" src="{{ comment.author.photo.url }}" alt="">
            {% else %}
                <img class="avatarka-core-com" src="/media/users/default.png" alt="">
            {% endif %}
            <p class="name">{{ comment.author.username }}</p>

        </div>
                                    </a> 

        <div class="line">
            <div class="comment-menu">
                <div class="burger"></div>

                <div class="dropdown">
                    <button 
                        class="reply-btn"
                        data-id="{{ comment.id }}"
                        data-username="{{ comment.author.username }}">
                        Ответить
                    </button>

                    {% if user == comment.author or user.is_superuser or user == post.author %}
                        <a href="{% url 'delete_comment' comment.id %}"
                           class="delete-comment-btn"
                           data-id="{{ comment.id }}">
                           Удалить
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <!-- ТЕКСТ -->
<p>{{ comment.content|highlight_mention|linebreaks }}</p>
    {% if comment.parent %}
        <p class="reply-info">
        </p>
    {% endif %}

    <small style="display:flex; justify-content:end;">
        {{ comment.time_create|date:"d.m.Y H:i" }}
    </small>

    <!-- КНОПКИ -->
    <div class="btns">
        <button class="like-btn" data-id="{{ comment.id }}"> 
            <span id="likes-{{ comment.id }}">
                {% if comment.total_likes >= 1 %}
                    ❤️{{ comment.total_likes }}
                {% endif %}
            </span>
        </button>

        <span class="heart-animation" style="display:none;">❤️</span>
    </div>

</div>

<!-- 🔥 ВАЖНО: ВЛОЖЕННЫЕ ОТВЕТЫ ВНЕ КНОПОК -->
{% for reply in comment.replies.all %}
    <div class="reply">
        {% include 'core/includes/comment.html' with comment=reply %}
    </div>
{% endfor %}

core/templates/core/includes/footer.html
    <ul> 
        <li><a href="{% url 'home' %}"> Главная страница</a></li>
            {% for m in menu %}
                {% if not forloop.last %}<li>{% else %}<li class="last"> {% endif %}
                    <a href="{% url m.url_name %}">{{ m.title }}</a>
                </li>
            {% endfor %}
    </ul>

core/templates/core/includes/nav.html
<header class="header2">
    
    <div class="header-container" >
        
        {% if user.is_authenticated %}
        <div style="display: flex; justify-content: space-between; width: 100%; align-items: center;" class="ff" >
<div style="display: flex;     background: #62696f00;
" >
            <a href="{% url 'users:profile' %}" class="user-inf" >                        {% if user.photo %}
                            <img class="avatarka2" src="{{ user.photo.url }}" alt="">
                        {% else %}
                            <img class="avatarka2" src="/media/users/default.png" alt="">
                        {% endif %}{{user.username}} </a>

                                    <a class="notif-a {% if user.unread_notifications_count > 0 %}has-notifications{% endif %}" href="{% url 'notifications' %}">
    <h2 class="notif-h2">
        🔔
        {% if user.unread_notifications_count > 0 %}
            <span class="notif-badge">{{ user.unread_notifications_count }}</span>
        {% else %}
            <span class="notif-badge zero">{{ user.unread_notifications_count }}</span>
        {% endif %}
    </h2>
</a>

</div>


<div style="display: flex;     background: #62696f00;
">

            <a href="/core" class="logo"><h1 class="logo-h1">⌂</h1></a>
            <a href="{% url 'users:logout' %}">Выйти</a>
</div>
        </div>



        {% else %}
        <a href="/" class="h1-logo"><h1 class="h1-logo">VΛULT</h1></a>
            <nav class="auth">
                {% if request.path != '/users/login/' and request.path != '/login/' %}
                    <a class="log-in-out" href="{% url 'users:login' %}">Войти</a>
                            {% endif %}

                {% if request.path != '/users/register/' and request.path != '/register/' %}
                <a class="log-in-out" href="{% url 'users:register' %}">Регистрация</a>
                {% endif %}
        {% endif %}
            </nav>
    </div>
</header>